#!/bin/bash

INPUT_FILE_1=''
INPUT_FILE_2=''

OUTPUT_FILE_1=''
OUTPUT_FILE_2=''


ADAPTER_SEQUENCE='GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGCCATGCATCTCGTATGCCGTCTTCTGCTTG'
PAIR_ADAPTER_SEQUENCE'GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGCCATGCATCTCGTATGCCGTCTTCTGCTTG'

#Path to CutAdapt
CUTADAPT_PATH='~/.local/bin/cutadapt'

# adapt trimming
$CUTADAPT_PATH \
-a $ADAPTER_SEQUENCE \
-A $PAIR_ADAPTER_SEQUENCE \
-o $OUTPUT_FILE_1 \
-p $OUTPUT_FILE_2 \
$INPUT_FILE_1 $INPUT_FILE_2 > TN1511D0795_1.cutadapt.log